services:
  ml_service:
    restart: always
    image: ml_od_gpu
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - d_v2:/datasets
      - w_v2:/weight
    ports:
      - "5001:5001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: flask run --host=0.0.0.0 --port=5001
networks:
  default:
    driver: bridge
volumes:
  d_v2:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/data/datasets/
  w_v2:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/data/weights/

